on:
  push:
    branches:
      - main
      
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
      upload_url: ${{ steps.release-please.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: node
          package-name: release-please-action


  build-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.releases_created
    container: fedora:latest
    strategy:
      matrix:
        major_version: [ 38 ]
        image_name: [silverblue-main, kinoite-main, vauxite-main, sericea-main, lxqt-main, mate-main]
    steps:
      - uses: actions/checkout@v3
      - name: Generate ISO  
        uses: ublue-os/isogenerator@main
        id: isogenerator
        with:
          image-name: ${{ matrix.image_name }}-${{ matrix.major_version }}
          installer-repo: development
          installer-major-version: ${{ matrix.major_version }}
          kickstart-file-path: ${{ matrix.image_name }}.ks
      - name: Upload ISO
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run:
          gh release upload ${{ needs.release-please.outputs.tag }} ./${{ steps.isogenerator.outputs.iso-path }} -R ublue-os/main
      - name: Upload SHA256SUM
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run:
          gh release upload ${{ needs.release-please.outputs.tag }} ./${{ steps.isogenerator.outputs.sha256sum-path }} -R ublue-os/main 
