name: Generate ISO

on:
  pull_request:
  #release:
  #  types: [published]

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container: fedora:latest
    strategy:
      matrix:
        fedora-version: [ 37 ]
    steps:
      - uses: actions/checkout@v3

      - uses: ublue-os/isogenerator@main
        id: isogenerator
        with:
          image-name: example-${{ matrix.fedora-version }}
          installer-major-version: 38
          installer-repo: development
          kickstart-file-path: ublue.ks

      - uses: actions/upload-artifact@v3
        with:
          name: example-${{ matrix.fedora-version }}
          path: ${{ steps.isogenerator.outputs.iso-path }}
