name: Generate ISO

on:
  pull_request:
  #release:
  #  types: [published]

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3

      - uses: ublue-os/isogenerator@cache-everything-iso
        id: isogenerator
        with:
          image-name: bluefin-38
          installer-major-version: 38
          installer-repo: development
          kickstart-file-path: ublue.ks

      - uses: actions/upload-artifact@v3
        with:
          name: bluefin-38-iso
          path: ${{ steps.isogenerator.outputs.iso-path }}
